using System.IO;
using System.Collections.Generic;
using SFGraphics.GLObjects.Shaders;
using OpenTK.Graphics.OpenGL;

namespace StudioSB.Rendering
{
    public class ShaderManager
    {
        private static Dictionary<string, Shader> shaderByName = new Dictionary<string, Shader>();

        /// <summary>
        /// Gets the shader by name
        /// </summary>
        /// <param name="name"></param>
        /// <returns>shader with specified name and null otherwise </returns>
        public static Shader GetShader(string name)
        {
            if (shaderByName.ContainsKey(name))
                return shaderByName[name];
            else
                return null;
        }

        public static void SetUpShaders()
        {
            shaderByName.Clear();

            Shader rModel = CreateRModelShader();
            shaderByName.Add("UltimateModel", rModel);

            Shader rModelUv = CreateRModelUvShader();
            shaderByName.Add("UltimateModelUV", rModelUv);

            // TODO: This shader can be generated by SFGraphics.
            Shader rModelDebug = CreateRModelDebugShader();
            shaderByName.Add("UltimateModelDebug", rModelDebug);

            Shader textureShader = CreateTextureShader();
            shaderByName.Add("Texture", textureShader);

            Shader boneShader = CreateBoneShader();
            shaderByName.Add("Bone", boneShader);

            Shader textShader = CreateTextShader();
            shaderByName.Add("Text", textShader);

            foreach (var pair in shaderByName)
            {
                if (!pair.Value.LinkStatusIsOk)
                {
                    System.Diagnostics.Debug.WriteLine(pair.Key);
                    System.Diagnostics.Debug.WriteLine(pair.Value.GetErrorLog());
                }
            }
        }

        private static Shader CreateTextShader()
        {
            Shader textShader = new Shader();
            textShader.LoadShader(File.ReadAllText("Shaders/Text.frag"), ShaderType.FragmentShader);
            textShader.LoadShader(File.ReadAllText("Shaders/Text.vert"), ShaderType.VertexShader);
            return textShader;
        }

        private static Shader CreateBoneShader()
        {
            Shader boneShader = new Shader();
            boneShader.LoadShader(File.ReadAllText("Shaders/Bone.frag"), ShaderType.FragmentShader);
            boneShader.LoadShader(File.ReadAllText("Shaders/Bone.vert"), ShaderType.VertexShader);
            return boneShader;
        }

        private static Shader CreateTextureShader()
        {
            Shader textureShader = new Shader();
            textureShader.LoadShader(File.ReadAllText("Shaders/Texture.frag"), ShaderType.FragmentShader);
            textureShader.LoadShader(File.ReadAllText("Shaders/Texture.vert"), ShaderType.VertexShader);
            textureShader.LoadShader(File.ReadAllText("Shaders/Gamma.frag"), ShaderType.FragmentShader);
            return textureShader;
        }

        private static Shader CreateRModelDebugShader()
        {
            Shader rModelDebug = new Shader();
            rModelDebug.LoadShader(File.ReadAllText("Shaders/UltimateModelDebug.frag"), ShaderType.FragmentShader);
            rModelDebug.LoadShader(File.ReadAllText("Shaders/UltimateModel.geom"), ShaderType.GeometryShader);
            rModelDebug.LoadShader(File.ReadAllText("Shaders/NormalMap.frag"), ShaderType.FragmentShader);
            rModelDebug.LoadShader(File.ReadAllText("Shaders/UltimateModel.vert"), ShaderType.VertexShader);
            rModelDebug.LoadShader(File.ReadAllText("Shaders/Gamma.frag"), ShaderType.FragmentShader);
            rModelDebug.LoadShader(File.ReadAllText("Shaders/Wireframe.frag"), ShaderType.FragmentShader);
            rModelDebug.LoadShader(File.ReadAllText("Shaders/TextureLayers.frag"), ShaderType.FragmentShader);
            return rModelDebug;
        }

        private static Shader CreateRModelUvShader()
        {
            Shader rModelUv = new Shader();
            rModelUv.LoadShader(File.ReadAllText("Shaders/UltimateModelUV.vert"), ShaderType.VertexShader);
            rModelUv.LoadShader(File.ReadAllText("Shaders/UltimateModel.geom"), ShaderType.GeometryShader);
            rModelUv.LoadShader(File.ReadAllText("Shaders/UltimateModelUV.frag"), ShaderType.FragmentShader);
            rModelUv.LoadShader(File.ReadAllText("Shaders/NormalMap.frag"), ShaderType.FragmentShader);
            rModelUv.LoadShader(File.ReadAllText("Shaders/Wireframe.frag"), ShaderType.FragmentShader);
            return rModelUv;
        }

        private static Shader CreateRModelShader()
        {
            Shader rModel = new Shader();
            rModel.LoadShader(File.ReadAllText("Shaders/UltimateModel.vert"), ShaderType.VertexShader);
            rModel.LoadShader(File.ReadAllText("Shaders/UltimateModel.geom"), ShaderType.GeometryShader);
            rModel.LoadShader(File.ReadAllText("Shaders/UltimateModel.frag"), ShaderType.FragmentShader);
            rModel.LoadShader(File.ReadAllText("Shaders/Gamma.frag"), ShaderType.FragmentShader);
            rModel.LoadShader(File.ReadAllText("Shaders/NormalMap.frag"), ShaderType.FragmentShader);
            rModel.LoadShader(File.ReadAllText("Shaders/Wireframe.frag"), ShaderType.FragmentShader);
            rModel.LoadShader(File.ReadAllText("Shaders/TextureLayers.frag"), ShaderType.FragmentShader);
            return rModel;
        }
    }
}
